import os

INPUT_DIR = "input"
OUTPUT_DIR = "output"
CONTAINER_NAME = "massspec-pipeline:latest"

MASS_SPEC_URL = "https://storage.yandexcloud.net/students-common/mass_spec_results.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJELqVUR2I4aFR9yju0lZmQ%2F20251129%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20251129T075802Z&X-Amz-Expires=2592000&X-Amz-Signature=8696243c988ba07aaf3b8c3bbf6ef9eedaff7c5d6e4364aea6087493c19e3e39&X-Amz-SignedHeaders=host&response-content-disposition=attachment"

SAMPLE_METADATA_URL = "https://storage.yandexcloud.net/students-common/sample_metadata.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJELqVUR2I4aFR9yju0lZmQ%2F20251129%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20251129T075822Z&X-Amz-Expires=2592000&X-Amz-Signature=10e1273d1fcbd5cba59ca00125eb26a4406c14a0ce39c97bcdd5a266493e8015&X-Amz-SignedHeaders=host&response-content-disposition=attachment"

rule all:
    input:
        "output/anti_left_join.csv",
        "output/anti_right_join.csv",
        "output/anti_outer_join.csv"

rule download_data:
    output:
        mass_spec = INPUT_DIR + "/mass_spec_results.csv",
        sample_meta = INPUT_DIR + "/sample_metadata.csv"
    shell:
        """
        mkdir -p {INPUT_DIR}
        curl -o {output.mass_spec} "{MASS_SPEC_URL}"
        curl -o {output.sample_meta} "{SAMPLE_METADATA_URL}"
        """

rule build_container:
    output:
        touch("docker_built")
    shell:
        """
        docker build -t {CONTAINER_NAME} .
        touch docker_built
        """

rule run_analysis:
    input:
        mass_spec = INPUT_DIR + "/mass_spec_results.csv",
        sample_meta = INPUT_DIR + "/sample_metadata.csv",
        container_ready = "docker_built"
    output:
        left = OUTPUT_DIR + "/anti_left_join.csv",
        right = OUTPUT_DIR + "/anti_right_join.csv",
        outer = OUTPUT_DIR + "/anti_outer_join.csv"
    shell:
        """
        mkdir -p {OUTPUT_DIR}
        docker run --rm \
            -u $(id -u):$(id -g) \
            -v $(pwd)/{INPUT_DIR}:/data/input \
            -v $(pwd)/{OUTPUT_DIR}:/data/output \
            {CONTAINER_NAME} \
            Rscript /app/script.R
        """